### ISSUE TITLE
Исправить ограничения согласно замечаниям преподавателя

### ISSUE THREAD

**Issue by kereeshkacxz** [kereeshkacxz/dndl#13]
Добавить версии браузерам 
Добавить версии стеку технологии
Добавить FastApi 
Соотнести пункт 8.3 требований с ограничениями
Конкретизировать устройства и версии для них
Пункт 8 от противного 
Написать вид доступа к персонажам

**Comment by AmjedKhaled165** [comment]
This might help:This file might fix it
https://bit.ly/4gx42eQ

you may need to install the c compiler
